name: Workflow Variables Example

on: push

env:
  APP_NAME: MyEcommerceApp
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: Production
    steps:
      - name: Show workflow variables
        env:
          TEMP_MESSAGE: "Hello from this Step level Variable"
        
        run: |
          echo "App name: $APP_NAME"
          echo "Node version: $NODE_VERSION"
          echo "Enviroment: $BUILD_ENV"
          echo "$TEMP_MESSAGE"
          echo "Repo Level Variable: ${{ vars.MY_REPO_VAR }}"
          echo "app URL is: ${{ vars.APP_URL }}"
